FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/simple-video-viewer/package.json frontend/simple-video-viewer/package-lock.json ./
RUN npm ci

COPY frontend/simple-video-viewer/ ./

ARG REACT_APP_API_BASE_URL=
ARG REACT_APP_WS_BASE_URL=
ARG REACT_APP_EDGE_ID=edge-default
ARG REACT_APP_WEBRTC_ICE_SERVERS_JSON=[{"urls":"stun:stun.l.google.com:19302"}]

ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_WS_BASE_URL=$REACT_APP_WS_BASE_URL
ENV REACT_APP_EDGE_ID=$REACT_APP_EDGE_ID
ENV REACT_APP_WEBRTC_ICE_SERVERS_JSON=$REACT_APP_WEBRTC_ICE_SERVERS_JSON

RUN npm run build

FROM nginx:1.27-alpine

COPY deploy/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
