from __future__ import annotations

from enum import Enum


class OperationMode(str, Enum):
    AUTOMATIC = "AUTOMATIC"
    MAINTENANCE = "MAINTENANCE"
    STOPPED = "STOPPED"


class RiskLevel(str, Enum):
    SAFE = "SAFE"
    NOTICE = "NOTICE"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    LOTO_RISK_DETECTED = "LOTO_RISK_DETECTED"


class ActionType(str, Enum):
    POWER_ON = "POWER_ON"
    POWER_OFF = "POWER_OFF"
    REDUCE_SPEED_50 = "REDUCE_SPEED_50"
    RESUME_FULL_SPEED = "RESUME_FULL_SPEED"

    TRIGGER_ALARM_MEDIUM = "TRIGGER_ALARM_MEDIUM"
    TRIGGER_ALARM_HIGH = "TRIGGER_ALARM_HIGH"
    TRIGGER_ALARM_CRITICAL = "TRIGGER_ALARM_CRITICAL"

    LOCK_SYSTEM = "LOCK_SYSTEM"

    LOG_CRITICAL_SENSOR = "LOG_CRITICAL_SENSOR"
    LOG_CRITICAL_FALLING = "LOG_CRITICAL_FALLING"
    LOG_LOTO_ACTIVE = "LOG_LOTO_ACTIVE"
    LOG_MAINTENANCE_SAFE = "LOG_MAINTENANCE_SAFE"
    LOG_INTRUSION_SLOWDOWN = "LOG_INTRUSION_SLOWDOWN"
    LOG_CROUCHING_WARN = "LOG_CROUCHING_WARN"
    LOG_NORMAL_OPERATION = "LOG_NORMAL_OPERATION"
